nav: auto
toc: true
site:
  name: Dokumentaro
  # base_url: https://dokumentaro.baldr.net
  atom_feed: false
  enable_sitemap: true
  lang: en
  locale: "en_US.utf8"
  nav_enabled: true
  heading_anchors: true
  back_to_top: true
  back_to_top_text: Back to top
  color_scheme: default
  color_scheme_switcher: true
  enable_copy_code_button: true
  last_edit_time_format: "%Y-%m-%d %H:%M"
  search_enabled: true
  search_placeholder: Search this website
  tags_enabled: true
  aux_links_new_tab: false
  nav_external_links_new_tab: false
  last_edit_timestamp: false
markdown_extensions:
  - sane_lists
  - toc
  - pymdownx.extra
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.blocks.admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tasklist
# For the mermaid config below, see
# https://facelessuser.github.io/pymdown-extensions/extras/mermaid/
markdown_extension_configs:
  pymdownx.highlight:
    use_pygments: true
  pymdownx.superfences:
    preserve_tabs: true
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  pymdownx.blocks.admonition:
    types:
      # Defaults: note, attention, caution, danger, error, tip, hint, warning.
      # Adding abstract, bug, example, failure, important, info, new,
      # question, quote, success.
      - note
      - attention
      - caution
      - danger
      - error
      - tip
      - hint
      - warning
      - abstract
      - bug
      - example
      - failure
      - important
      - name: info
        title: "Information"
      - new
      - question
      - quote
      - success
  toc:
    toc_depth: "2-3"
cleanup_commands:
  - "npx -y pagefind --site htdocs"
use_dart_sass: true
