nav: auto
toc: true
#pandoc: true
site:
  name: Dokumentaro
  # title -- mostly just an alternative to site.name
  base_url: https://dokumentaro.baldr.net
  lang: en
  locale: "en_US.utf8"
  nav_enabled: true
  heading_anchors: true
  back_to_top: true
  back_to_top_text: Back to top
  color_scheme: default
  enable_copy_code_button: true
  last_edit_time_format: "%Y-%m-%d %H:%M"
  search_enabled: true
  search_placeholder: Search Dokumentaro
  tags_enabled: true
  #tag_urls:
  #  list: '/tags/'
  #  item: '/tags/{}/'
  aux_links:
    - title: Mbl
      url: https://www.mbl.is/frettir/
  aux_links_new_tab: true
  mermaid:
    version: 11.4.1
  nav_external_links:
    - title: wmk on github
      url: https://github.com/bk/wmk
    - title: wmk documentation
      url: https://wmk.baldr.net/
  nav_external_links_new_tab: true
  last_edit_timestamp: true
  # Other settings:
  # favicon_ico
  # footer_content
  # ga_tracking
  # ga_tracking_anonymize_ip
  # gh_edit_link
  # gh_edit_link_text
  # gh_edit_view_mode
  # logo
  # mermaid
  # nav_footer_text
  # search -- object: button, rel_url, focus_shortcut_key, preview_words_before, preview_words_after
  # search_tokenizer_separator
markdown_extensions:
  - sane_lists
  - toc
  - pymdownx.extra
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.blocks.admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tasklist
# For the mermaid config, see https://facelessuser.github.io/pymdown-extensions/extras/mermaid/
markdown_extension_configs:
  pymdownx.highlight:
    use_pygments: true
  pymdownx.superfences:
    preserve_tabs: true
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  pymdownx.blocks.admonition:
    types:
      # Defaults: note, attention, caution, danger, error, tip, hint, warning.
      # Adding abstract, bug, example, failure, important, info, new,
      # question, quote, success.
      - note
      - attention
      - caution
      - danger
      - error
      - tip
      - hint
      - warning
      - abstract
      - bug
      - example
      - failure
      - important
      - name: info
        title: "Information"
      - new
      - question
      - quote
      - success
  toc:
    toc_depth: "2-3"
cleanup_commands:
  - "npx -y pagefind --site htdocs"
