theme: dokumentaro
site:
  base_url: https://dokumentaro.baldr.net
  search_placeholder: Search Dokumentaro
  aux_links:
    - title: Dokumentaro on GitHub
      url: https://github.com/bk/dokumentaro
  aux_links_new_tab: true
  mermaid:
    version: 11.4.1
  nav_external_links:
    - title: wmk on github
      url: https://github.com/bk/wmk
    - title: wmk documentation
      url: https://wmk.baldr.net/
  nav_external_links_new_tab: true
  last_edit_timestamp: true
  # Other settings:
  # ga_tracking
  # ga_tracking_anonymize_ip
  # gh_edit_link
  # gh_edit_link_text
  # gh_edit_view_mode
  # nav_footer_text
  # search -- object: button, rel_url, focus_shortcut_key, preview_words_before, preview_words_after
  # search_tokenizer_separator
