theme: dokumentaro
site:
  base_url: https://dokumentaro.baldr.net
  search_placeholder: Search Dokumentaro
  aux_links:
    - title: Dokumentaro on GitHub
      url: https://github.com/bk/dokumentaro
  aux_links_new_tab: true
  mermaid:
    version: 11.4.1
  nav_external_links:
    - title: wmk on github
      url: https://github.com/bk/wmk
    - title: wmk documentation
      url: https://wmk.baldr.net/
  nav_external_links_new_tab: true
  last_edit_timestamp: true
  gh_edit_link: https://github.com/bk/dokumentaro/edit/main/docs/content
  gh_edit_link_text: Edit on GitHub
